# screen
WIDTH = 800
HEIGHT = 600
SIZE_SCREEN = (WIDTH, HEIGHT)
CENTER_SCREEN = (WIDTH // 2, HEIGHT // 2)

# game config
FPS = 60
GRAVITY = 1

# player

WIDTH_PLAYER = 25
HEIGHT_PLAYER = 25
SIZE_PLAYER = (WIDTH_PLAYER, HEIGHT_PLAYER)

# coins
SIZE_COIN = (15, 20)

# enemies
SIZE_GOOMBAS = (WIDTH_PLAYER, HEIGHT_PLAYER)

# buttons
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50

# colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
